name: random_slot_game
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  hooks_riverpod: ^1.0.0-dev.7
  flutter_hooks: ^0.18.0
  sizer: ^2.0.13
  flex_color_scheme: ^3.0.1
  equatable: ^2.0.3
  freezed_annotation: ^0.14.3
  intl: ^0.17.0
  sqflite: ^2.0.0+4
  path: ^1.8.0
  dartz: ^0.10.0
  uuid: ^3.0.4
  google_mobile_ads: ^0.13.5
  package_info_plus: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.2
  freezed: ^0.14.5
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path_android: "asset/image/android_icon.png"
  image_path_ios: "asset/image/ios_icon.png"
  adaptive_icon_background: "#843D0B"
  adaptive_icon_foreground: "asset/image/icon.png"

flutter:
  uses-material-design: true
  generate: true
  assets:
    - asset/image/
